// Generated by ReScript, PLEASE EDIT WITH CARE


function UIUtils$RenderIf(props) {
  if (props.condition) {
    return props.children;
  } else {
    return null;
  }
}

var RenderIf = {
  make: UIUtils$RenderIf
};

export {
  RenderIf ,
}
/* No side effect */
